sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.1.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.1.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.1.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.1.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.2.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.2.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.2.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.2.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.3.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.3.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.3.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.3.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.4.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.4.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.4.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.4.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.5.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.5.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.5.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.5.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.6.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.6.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.6.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.6.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.7.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.7.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.7.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.7.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.8.0_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.8.0'
  - env:
    - DOCKER_JOB_NAME='tensorforce_1.8.0_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:1.8.0-py3'
  - env:
    - DOCKER_JOB_NAME='tensorforce_latest_py2'
    - DOCKER_IMAGE='tensorflow/tensorflow:latest'
  - env:
    - DOCKER_JOB_NAME='tensorforce_latest_py3'
    - DOCKER_IMAGE='tensorflow/tensorflow:latest-py3'

before_install:
  - docker pull ${DOCKER_IMAGE}
  - docker run -d --rm --name ${DOCKER_JOB_NAME} -v $(pwd):/roomai ${DOCKER_IMAGE} /bin/bash -c 'while true; do sleep 1; done';

install:
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'python -m pip install -U pip';
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'cd /roomai && python -m pip install .';

script:
  - docker exec ${DOCKER_JOB_NAME}  /bin/sh -c 'cd /roomai && python -m unittest discover -s tests';

notifications:
  email:
    recipients:
      - lili1987mail@gmai.com
    on_success: never
    on_failure: always

